"""Fetch upstream credentials from GCP Secret Manager at container startup.

Runs as the `bootstrap-secrets` s6 oneshot. Reads a base64-or-raw service
account JSON from $GOOGLE_APPLICATION_CREDENTIALS_JSON, hits Secret Manager in
project `ai-sidecar-nt`, and writes a key=value env file to
/run/coder-agents-sidecars/secrets.env (mode 600). All longruns then source
that file in their s6 run scripts.

Exits non-zero on:
  - missing $GOOGLE_APPLICATION_CREDENTIALS_JSON
  - any secret missing from Secret Manager
  - any secret value equal to REPLACE_ME (the placeholder created by the GCP
    setup script — fail loudly so we don't ship with placeholder creds).
"""

from __future__ import annotations

import base64
import json
import os
import sys
import tempfile
from pathlib import Path

from google.cloud import secretmanager
from google.oauth2 import service_account

GCP_PROJECT = os.environ.get("SIDECAR_GCP_PROJECT", "ai-sidecar-nt")
# Required secrets: any missing / empty / REPLACE_ME value fails the boot.
SECRETS = [
    "SIDECAR_SHARED_API_KEY",
    "CLAUDE_CODE_OAUTH_TOKEN",
    "GROQ_API_KEY",
    "CEREBRAS_API_KEY",
    "CODESTRAL_API_KEY",
    "ZEN_API_KEY",
    "AGENTMEMORY_MCP_API_KEY",
]
# Optional secrets: tolerated when missing from Secret Manager or set to
# REPLACE_ME / empty. Each absent optional secret is still written to
# secrets.env (as empty) so dependent run scripts can `source` the file
# without tripping `set -u`. Use this for credentials the operator may not
# have provisioned yet — the consuming service is responsible for
# degrading gracefully when its optional secret is empty.
OPTIONAL_SECRETS = [
    "CODER_API_TOKEN",
]
OUT_PATH = Path(os.environ.get("SIDECAR_SECRETS_OUT", "/run/coder-agents-sidecars/secrets.env"))
PLACEHOLDER = "REPLACE_ME"


def _log(msg: str) -> None:
    print(f"[bootstrap-secrets] {msg}", file=sys.stderr, flush=True)


def _load_sa_credentials() -> service_account.Credentials:
    raw = os.environ.get("GOOGLE_APPLICATION_CREDENTIALS_JSON", "").strip()
    if not raw:
        _log("GOOGLE_APPLICATION_CREDENTIALS_JSON not set; cannot fetch secrets")
        sys.exit(1)
    # Accept either raw JSON or base64-encoded JSON, in that order.
    try:
        info = json.loads(raw)
    except json.JSONDecodeError:
        try:
            info = json.loads(base64.b64decode(raw).decode("utf-8"))
        except Exception as exc:
            _log(f"GOOGLE_APPLICATION_CREDENTIALS_JSON neither JSON nor base64-JSON: {exc}")
            sys.exit(1)
    try:
        return service_account.Credentials.from_service_account_info(
            info,
            scopes=["https://www.googleapis.com/auth/cloud-platform"],
        )
    except Exception as exc:
        _log(f"failed to build SA credentials: {exc}")
        sys.exit(1)


def _shell_quote(value: str) -> str:
    """Single-quote a value for safe sourcing in bash."""
    return "'" + value.replace("'", "'\\''") + "'"


def main() -> None:
    creds = _load_sa_credentials()
    client = secretmanager.SecretManagerServiceClient(credentials=creds)

    fetched: dict[str, str] = {}
    for name in SECRETS + OPTIONAL_SECRETS:
        is_optional = name in OPTIONAL_SECRETS
        resource = f"projects/{GCP_PROJECT}/secrets/{name}/versions/latest"
        try:
            resp = client.access_secret_version(name=resource)
        except Exception as exc:
            if is_optional:
                _log(f"optional {name} not retrievable ({exc}); writing empty")
                fetched[name] = ""
                continue
            _log(f"failed to fetch {name}: {exc}")
            sys.exit(1)
        value = resp.payload.data.decode("utf-8")
        if value == PLACEHOLDER or not value:
            if is_optional:
                _log(f"optional {name} is empty or {PLACEHOLDER}; writing empty")
                fetched[name] = ""
                continue
            reason = PLACEHOLDER if value == PLACEHOLDER else "empty"
            _log(f"{name} is {reason} — refusing to start")
            sys.exit(1)
        fetched[name] = value

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    # Write to a tmpfile in the same dir and atomically rename so concurrent
    # readers never see a half-written file.
    tmp_fd, tmp_path = tempfile.mkstemp(prefix=".secrets.", dir=str(OUT_PATH.parent))
    try:
        with os.fdopen(tmp_fd, "w") as fh:
            fh.write("# Generated by bootstrap_secrets.py. Do not edit by hand.\n")
            for key, value in fetched.items():
                fh.write(f"export {key}={_shell_quote(value)}\n")
        os.chmod(tmp_path, 0o600)
        os.replace(tmp_path, OUT_PATH)
    except Exception:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass
        raise
    _log(f"wrote {len(fetched)} secrets to {OUT_PATH}")


if __name__ == "__main__":
    main()
